name: bs
description: "testing flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  provider: ^6.1.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  lottie: ^3.0.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  timeago: ^3.7.0
  image_picker: ^1.0.0
  camera: ^0.11.1
  device_info_plus: ^11.4.0
  collection: ^1.17.0
  google_sign_in_web: ^0.12.4+4
  dio: ^5.0.0 # O la versión más reciente disponible
  crypto: ^3.0.1 # O la versión más reciente disponible
  path: ^1.8.2 # O la versión más reciente disponible
  flutter_speed_dial: ^7.0.0
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  geolocator: ^14.0.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - lib/assets/boomshot.png
    - lib/assets/ic_boomshoot_camera.png
    - lib/assets/main_scene.json # Asumiendo que es un archivo JSON de Lottie
    - .env