name: bs
description: "testing flutter"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.0
  camera: ^0.11.1
  cloud_firestore: ^5.2.1
  cloudinary_public: ^0.23.1
  collection: ^1.17.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  dio: ^5.0.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  flutter_dotenv: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.1
  geolocator: ^14.0.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+4
  http: ^1.2.2
  image_picker: ^1.0.0
  intl: ^0.19.0
  lottie: ^3.0.0
  material_floating_search_bar_2: ^0.5.0
  path: ^1.8.2
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  share_plus: ^11.0.0
  shared_preferences: ^2.3.0
  timeago: ^3.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - lib/assets/boomshot.png
    - lib/assets/ic_boomshoot_camera.png
    - assets/main_scene.json
    - .env
    - assets/icons/profile.json
    - assets/icons/loading.json
    - assets/icons/home.json
    - assets/icons/camera.json
    - assets/icons/menu.json
    - assets/icons/settings.json
    - assets/google_logo.png